import type { Metadata } from 'next';
import { tiktok } from '@growth-agent/services';
import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  EmptyState,
} from '@growth-agent/ui';
import { RunTikTokAnalystButton } from '@/components/app/tiktok/tiktok-actions';
import { TikTokEmpty } from '@/components/app/tiktok/tiktok-empty';
import { requireActiveOrg } from '@/lib/auth';
import { analystConfigured } from '@/lib/tiktok';
import { loadTikTokState } from '@/lib/tiktok-state';

export const metadata: Metadata = { title: 'TikTok — Content opportunities' };

interface AnalysisOut {
  captionIdeas?: Array<{ caption: string; rationale: string }>;
  hashtagSuggestions?: Array<{ hashtags: string[]; rationale: string }>;
  contentThemes?: Array<{ theme: string; rationale: string }>;
  postingRecommendations?: Array<{ suggestion: string; rationale: string }>;
  repurposingRecommendations?: Array<{ suggestion: string; rationale: string }>;
}

export default async function TikTokOpportunitiesPage() {
  const { org } = await requireActiveOrg();
  const state = await loadTikTokState(org.id);
  if (state.kind !== 'ready') return <TikTokEmpty state={state} />;

  const [ideas, run] = await Promise.all([
    tiktok.listContentIdeas(org.id),
    tiktok.latestAnalystRun(org.id),
  ]);
  const a = (run?.output ?? null) as AnalysisOut | null;
  const nothing =
    ideas.length === 0 &&
    !a?.captionIdeas?.length &&
    !a?.hashtagSuggestions?.length &&
    !a?.contentThemes?.length &&
    !a?.postingRecommendations?.length;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-muted-foreground text-sm">
          Ideas and suggestions generated by the TikTok Analyst Agent from your synced data —
          clearly separate from your actual metrics.
        </p>
        <RunTikTokAnalystButton disabled={!analystConfigured()} />
      </div>

      {nothing ? (
        <EmptyState
          title="No opportunities generated yet."
          description={
            analystConfigured()
              ? 'Sync your account, then run the analysis to generate content, caption, hashtag, theme, posting, and repurposing suggestions.'
              : 'The analyst needs an AI provider key. Once configured, run the analysis.'
          }
        />
      ) : null}

      {ideas.length > 0 ? (
        <Section title="Content ideas">
          <div className="grid gap-3 sm:grid-cols-2">
            {ideas.map((i) => (
              <Card key={i.id}>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between gap-2">
                    <CardTitle className="text-sm">{i.title}</CardTitle>
                    <Badge variant="outline">{i.kind}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="text-muted-foreground text-xs">
                  {i.rationale}
                  {i.keywords.length ? (
                    <p className="text-foreground mt-2">Keywords: {i.keywords.join(', ')}</p>
                  ) : null}
                </CardContent>
              </Card>
            ))}
          </div>
        </Section>
      ) : null}

      {a?.captionIdeas?.length ? (
        <ListSection
          title="Caption ideas"
          items={a.captionIdeas.map((c) => ({ head: c.caption, body: c.rationale }))}
        />
      ) : null}
      {a?.hashtagSuggestions?.length ? (
        <ListSection
          title="Hashtag suggestions"
          items={a.hashtagSuggestions.map((h) => ({
            head: h.hashtags.map((x) => `#${x.replace(/^#/, '')}`).join(' '),
            body: h.rationale,
          }))}
        />
      ) : null}
      {a?.contentThemes?.length ? (
        <ListSection
          title="Content themes"
          items={a.contentThemes.map((t) => ({ head: t.theme, body: t.rationale }))}
        />
      ) : null}
      {a?.postingRecommendations?.length ? (
        <ListSection
          title="Posting recommendations"
          items={a.postingRecommendations.map((p) => ({ head: p.suggestion, body: p.rationale }))}
        />
      ) : null}
      {a?.repurposingRecommendations?.length ? (
        <ListSection
          title="Repurposing recommendations"
          items={a.repurposingRecommendations.map((p) => ({
            head: p.suggestion,
            body: p.rationale,
          }))}
        />
      ) : null}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-sm font-medium">{title}</h2>
      {children}
    </section>
  );
}

function ListSection({
  title,
  items,
}: {
  title: string;
  items: Array<{ head: string; body: string }>;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription>{items.length} item(s)</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {items.map((it, i) => (
          <div key={i} className="border-border border-l-2 pl-3">
            <p className="text-sm font-medium">{it.head}</p>
            <p className="text-muted-foreground text-xs">{it.body}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
