import type { Metadata } from 'next';
import { youtube } from '@growth-agent/services';
import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  EmptyState,
} from '@growth-agent/ui';
import { RunAnalystButton } from '@/components/app/youtube/youtube-actions';
import { YouTubeEmpty } from '@/components/app/youtube/youtube-empty';
import { requireActiveOrg } from '@/lib/auth';
import { analystConfigured } from '@/lib/youtube';
import { loadYouTubeState } from '@/lib/youtube-state';

export const metadata: Metadata = { title: 'YouTube — Content opportunities' };

interface AnalysisOut {
  topicSuggestions?: Array<{ topic: string; rationale: string }>;
  publishingRecommendations?: Array<{ suggestion: string; rationale: string }>;
  titleSuggestions?: Array<{ suggestion: string; rationale: string; forVideoId?: string }>;
  descriptionSuggestions?: Array<{ suggestion: string; rationale: string; forVideoId?: string }>;
}

export default async function YouTubeOpportunitiesPage() {
  const { org } = await requireActiveOrg();
  const state = await loadYouTubeState(org.id);
  if (state.kind !== 'ready') return <YouTubeEmpty state={state} />;

  const [ideas, run] = await Promise.all([
    youtube.listYouTubeContentIdeas(org.id),
    youtube.latestAnalystRun(org.id),
  ]);
  const analysis = (run?.output ?? null) as AnalysisOut | null;
  const nothing =
    ideas.length === 0 &&
    !analysis?.topicSuggestions?.length &&
    !analysis?.publishingRecommendations?.length &&
    !analysis?.titleSuggestions?.length;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-muted-foreground text-sm">
          Generated by the YouTube Analyst Agent from your synced data. Every item cites the data it
          is based on.
        </p>
        <RunAnalystButton disabled={!analystConfigured()} />
      </div>

      {nothing ? (
        <EmptyState
          title="No opportunities generated yet."
          description={
            analystConfigured()
              ? 'Sync your channel, then run the analysis to generate topic, title, description, and publishing suggestions.'
              : 'The analyst needs an AI provider key. Once configured, run the analysis to generate suggestions.'
          }
        />
      ) : null}

      {ideas.length > 0 ? (
        <section className="space-y-3">
          <h2 className="text-sm font-medium">Content ideas</h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {ideas.map((i) => (
              <Card key={i.id}>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between gap-2">
                    <CardTitle className="text-sm">{i.title}</CardTitle>
                    <Badge variant="outline">{i.kind}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="text-muted-foreground text-xs">
                  {i.rationale}
                  {i.keywords.length ? (
                    <p className="text-foreground mt-2">Keywords: {i.keywords.join(', ')}</p>
                  ) : null}
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      ) : null}

      {analysis?.topicSuggestions?.length ? (
        <Suggestions
          title="Topic suggestions"
          items={analysis.topicSuggestions.map((t) => ({ head: t.topic, body: t.rationale }))}
        />
      ) : null}
      {analysis?.publishingRecommendations?.length ? (
        <Suggestions
          title="Publishing recommendations"
          items={analysis.publishingRecommendations.map((p) => ({
            head: p.suggestion,
            body: p.rationale,
          }))}
        />
      ) : null}
      {analysis?.titleSuggestions?.length ? (
        <Suggestions
          title="Title suggestions"
          items={analysis.titleSuggestions.map((t) => ({
            head: t.suggestion,
            body: `${t.rationale}${t.forVideoId ? ` (for video ${t.forVideoId})` : ''}`,
          }))}
        />
      ) : null}
      {analysis?.descriptionSuggestions?.length ? (
        <Suggestions
          title="Description suggestions"
          items={analysis.descriptionSuggestions.map((t) => ({
            head: t.suggestion,
            body: `${t.rationale}${t.forVideoId ? ` (for video ${t.forVideoId})` : ''}`,
          }))}
        />
      ) : null}
    </div>
  );
}

function Suggestions({
  title,
  items,
}: {
  title: string;
  items: Array<{ head: string; body: string }>;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription>{items.length} item(s)</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {items.map((it, i) => (
          <div key={i} className="border-border border-l-2 pl-3">
            <p className="text-sm font-medium">{it.head}</p>
            <p className="text-muted-foreground text-xs">{it.body}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
