import type { Metadata } from 'next';
import { youtube } from '@growth-agent/services';
import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  EmptyState,
} from '@growth-agent/ui';
import {
  DismissOpportunityButton,
  PromoteOpportunityButton,
  RegenerateOpportunitiesButton,
  RunAnalystButton,
} from '@/components/app/youtube/youtube-actions';
import { YouTubeEmpty } from '@/components/app/youtube/youtube-empty';
import { requireActiveOrg } from '@/lib/auth';
import { analystConfigured } from '@/lib/youtube';
import { loadYouTubeState } from '@/lib/youtube-state';

const CONFIDENCE_VARIANT: Record<string, 'default' | 'secondary' | 'outline'> = {
  HIGH: 'default',
  MEDIUM: 'secondary',
  LOW: 'outline',
};

export const metadata: Metadata = { title: 'YouTube — Content opportunities' };

interface AnalysisOut {
  topicSuggestions?: Array<{ topic: string; rationale: string }>;
  publishingRecommendations?: Array<{ suggestion: string; rationale: string }>;
  titleSuggestions?: Array<{ suggestion: string; rationale: string; forVideoId?: string }>;
  descriptionSuggestions?: Array<{ suggestion: string; rationale: string; forVideoId?: string }>;
}

export default async function YouTubeOpportunitiesPage() {
  const { org } = await requireActiveOrg();
  const state = await loadYouTubeState(org.id);
  if (state.kind !== 'ready') return <YouTubeEmpty state={state} />;

  const [ideas, run, opportunities] = await Promise.all([
    youtube.listYouTubeContentIdeas(org.id),
    youtube.latestAnalystRun(org.id),
    youtube.listYouTubeOpportunities(org.id, { status: 'SUGGESTED' }),
  ]);
  const analysis = (run?.output ?? null) as AnalysisOut | null;
  const nothing =
    ideas.length === 0 &&
    !analysis?.topicSuggestions?.length &&
    !analysis?.publishingRecommendations?.length &&
    !analysis?.titleSuggestions?.length;

  return (
    <div className="space-y-6">
      <section className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-sm font-medium">Content opportunities</h2>
            <p className="text-muted-foreground text-xs">
              Deterministic, evidence-backed opportunities derived from your own video history —
              each with a documented priority score, never a virality prediction.
            </p>
          </div>
          <RegenerateOpportunitiesButton />
        </div>
        {opportunities.length === 0 ? (
          <EmptyState
            title="No content opportunities yet."
            description="Sync your videos, then regenerate to identify evidence-backed opportunities from your own history."
          />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2">
            {opportunities.map((o) => (
              <Card key={o.id}>
                <CardHeader className="pb-2">
                  <div className="flex items-start justify-between gap-2">
                    <CardTitle className="text-sm">{o.title}</CardTitle>
                    <Badge variant={CONFIDENCE_VARIANT[o.confidence] ?? 'outline'}>
                      {o.confidence} confidence
                    </Badge>
                  </div>
                  <CardDescription className="text-xs">
                    Priority score {o.priorityScore.toFixed(2)} ·{' '}
                    {o.type.replace(/_/g, ' ').toLowerCase()}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-2 text-xs">
                  <p className="text-muted-foreground">{o.description}</p>
                  {o.recommendedActions.length > 0 ? (
                    <ul className="text-muted-foreground list-inside list-disc">
                      {o.recommendedActions.map((a, i) => (
                        <li key={i}>{a}</li>
                      ))}
                    </ul>
                  ) : null}
                  <div className="flex items-center gap-2 pt-1">
                    <PromoteOpportunityButton opportunityId={o.id} />
                    <DismissOpportunityButton opportunityId={o.id} />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </section>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-muted-foreground text-sm">
          Generated by the YouTube Analyst Agent from your synced data. Every item cites the data it
          is based on.
        </p>
        <RunAnalystButton disabled={!analystConfigured()} />
      </div>

      {nothing ? (
        <EmptyState
          title="No opportunities generated yet."
          description={
            analystConfigured()
              ? 'Sync your channel, then run the analysis to generate topic, title, description, and publishing suggestions.'
              : 'The analyst needs an AI provider key. Once configured, run the analysis to generate suggestions.'
          }
        />
      ) : null}

      {ideas.length > 0 ? (
        <section className="space-y-3">
          <h2 className="text-sm font-medium">Content ideas</h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {ideas.map((i) => (
              <Card key={i.id}>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between gap-2">
                    <CardTitle className="text-sm">{i.title}</CardTitle>
                    <Badge variant="outline">{i.kind}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="text-muted-foreground text-xs">
                  {i.rationale}
                  {i.keywords.length ? (
                    <p className="text-foreground mt-2">Keywords: {i.keywords.join(', ')}</p>
                  ) : null}
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      ) : null}

      {analysis?.topicSuggestions?.length ? (
        <Suggestions
          title="Topic suggestions"
          items={analysis.topicSuggestions.map((t) => ({ head: t.topic, body: t.rationale }))}
        />
      ) : null}
      {analysis?.publishingRecommendations?.length ? (
        <Suggestions
          title="Publishing recommendations"
          items={analysis.publishingRecommendations.map((p) => ({
            head: p.suggestion,
            body: p.rationale,
          }))}
        />
      ) : null}
      {analysis?.titleSuggestions?.length ? (
        <Suggestions
          title="Title suggestions"
          items={analysis.titleSuggestions.map((t) => ({
            head: t.suggestion,
            body: `${t.rationale}${t.forVideoId ? ` (for video ${t.forVideoId})` : ''}`,
          }))}
        />
      ) : null}
      {analysis?.descriptionSuggestions?.length ? (
        <Suggestions
          title="Description suggestions"
          items={analysis.descriptionSuggestions.map((t) => ({
            head: t.suggestion,
            body: `${t.rationale}${t.forVideoId ? ` (for video ${t.forVideoId})` : ''}`,
          }))}
        />
      ) : null}
    </div>
  );
}

function Suggestions({
  title,
  items,
}: {
  title: string;
  items: Array<{ head: string; body: string }>;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription>{items.length} item(s)</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {items.map((it, i) => (
          <div key={i} className="border-border border-l-2 pl-3">
            <p className="text-sm font-medium">{it.head}</p>
            <p className="text-muted-foreground text-xs">{it.body}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
