import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { reports } from '@growth-agent/services';
import { ReportSnapshotView } from '@/components/app/reports/report-snapshot-view';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Shared report',
  robots: { index: false, follow: false },
};

/**
 * Public, unauthenticated view of a shared report. `getReportForShare` returns a
 * REDACTED snapshot only — no account identifiers, no private figures — and
 * `null` for an unknown / expired / revoked token.
 */
export default async function SharedReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const shared = await reports.getReportForShare(token);
  if (!shared) notFound();

  return (
    <div className="mx-auto max-w-3xl px-4 py-10">
      <header className="mb-6">
        <p className="text-muted-foreground text-xs uppercase tracking-wide">Shared report</p>
        <h1 className="text-2xl font-semibold tracking-tight">{shared.title}</h1>
        <div className="mt-3 flex flex-wrap gap-2">
          <a
            href={`/r/${token}/export?format=pdf`}
            className="hover:bg-muted rounded border px-2 py-1 text-xs"
          >
            PDF
          </a>
          <a
            href={`/r/${token}/export?format=csv`}
            className="hover:bg-muted rounded border px-2 py-1 text-xs"
          >
            CSV
          </a>
        </div>
      </header>
      <ReportSnapshotView snapshot={shared.snapshot} isPublic />
      <footer className="text-muted-foreground mt-10 text-xs">
        Generated by Growth Agent. This shared copy is read-only and redacted.
      </footer>
    </div>
  );
}
